// src/integrations/supabase/client.ts

// This file is automatically generated. Do not edit it directly. // <-- You might need to ignore this comment temporarily to fix this
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use direct values instead of process.env
const supabaseUrl = "https://jyouplrevnwsnjprzdeg.supabase.co";
const supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5b3VwbHJldm53c25qcHJ6ZGVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMjg4NzEsImV4cCI6MjA1OTkwNDg3MX0.VQ3L8Xyrvt_oLmF0f1IrjYQZyG9MRryKDbmYAzZc0zk";

// Initialize Supabase client with error handling
let supabaseInstance;
try {
    supabaseInstance = createClient<Database>(supabaseUrl, supabaseAnonKey, {
        auth: {
            persistSession: true,
            autoRefreshToken: true,
        },
        global: {
            headers: {
                'x-client-info': 'learnify-med-skillz'
            }
        }
    });
    console.log('Supabase client initialized successfully');
} catch (error) {
    console.error('Error initializing Supabase client:', error);
    throw new Error('Failed to initialize Supabase client');
}

export const supabase = supabaseInstance;
export const SUPABASE_URL = supabaseUrl;
export const SUPABASE_PUBLISHABLE_KEY = supabaseAnonKey;